import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div id="header">
          <div id="bold-button"></div>
          <div id="links">
            <div className="button"></div>
            <div className="button"></div>
            <div className="button"></div>
            <div className="button"></div>
          </div>
        </div>
        <div id="landing">
          <div id="image"></div>
          <div id="container">
            <div id="text">
              <div id="title"></div>
              <div id="subtitle"></div>
              <div id="description"></div>
            </div>
            <div id="buttons-container">
              <div id="button-light"></div>
              <div id="button-bold"></div>
            </div>
          </div>
        </div>
        <div id="heroes">
          <div className="hero-item"></div>
          <div className="hero-item"></div>
          <div className="hero-item"></div>
          <div className="hero-item"></div>
        </div>
        <div id="image-grid">
          <div className="image"></div>
          <div className="image"></div>
          <div className="image"></div>
        </div>
        <div id="scroller-grid">
          <div id="text-container">
            <div id="title"></div>
            <div id="description"></div>
          </div>
          <div id="scroller-container">
            <div id="scroll-item"></div>
            <div id="scroll-item"></div>
            <div id="scroll-item"></div>
            <div id="scroll-item"></div>
          </div>
        </div>
        <div id="vertical-grid">
          <div className="grid-item">
            <div className="text-container">
              <div id="title"></div>
              <div id="description"></div>
            </div>
            <div id="image"></div>
          </div>
          <div className="grid-item">
            <div className="text-container">
              <div id="title"></div>
              <div id="description"></div>
            </div>
            <div id="image"></div>
          </div>
          <div className="grid-item">
            <div className="text-container">
              <div id="title"></div>
              <div id="description"></div>
            </div>
            <div id="image"></div>
          </div>
        </div>
        <div id="featured-container">
          <div id="text-container">
            <div id="title"></div>
            <div id="subtitle"></div>
            <div id="button"></div></div>
          <div id="image"></div>
        </div>
        <div id="div">
          <div id="links">
            <div id="image">
              <div id="title"></div>
              <div className="link"></div>
              <div className="link"></div>
              <div className="link"></div>
            </div>
            <div id="learn">
              <div id="title"></div>
              <div className="link"></div>
              <div className="link"></div>
              <div className="link"></div>
            </div>
            <div id="support">
              <div id="title"></div>
              <div className="link"></div>
              <div className="link"></div>
              <div className="link"></div>
            </div>
            <div id="company">
              <div id="title"></div>
              <div className="link"></div>
              <div className="link"></div>
              <div className="link"></div>
            </div>
            <div id="api">
              <div id="title"></div>
              <div className="link"></div>
              <div className="link"></div>
              <div className="link"></div>
            </div>
            <div id="page-divs">
              <div id="title"></div>
              <div className="link"></div>
              <div className="link"></div>
              <div className="link"></div>
            </div>
          </div>
          <div id="container-buttons">
            <div id="button-featured-container">
              <div className="button-featured"></div>
              <div className="button-featured"></div>
              <div className="button-featured"></div>
            </div>
            <div id="container-default-buttons">  
              <div className="button"></div>
              <div className="button"></div>
              <div className="button"></div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
